version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
    networks:
      - network
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    networks:
      - network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dockerpg@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "#123456"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - network

networks:
  network:
    driver: bridge
